# Generated by Django 5.2.1 on 2025-07-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome principal do produto, como aparecerá na nota e nas etiquetas.', max_length=200, unique=True, verbose_name='Nome do Produto')),
                ('estoque', models.PositiveIntegerField(default=0, help_text='A quantidade atual de unidades deste produto disponíveis para venda.', verbose_name='Quantidade em Estoque')),
                ('custo', models.DecimalField(decimal_places=2, help_text='O valor que você pagou pelo produto.', max_digits=10, verbose_name='Preço de Custo (R$)')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Margem de Lucro (%)')),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, verbose_name='Preço Final de Venda (R$)')),
                ('codigo_barras', models.CharField(blank=True, help_text='Digite um código de até 13 números ou deixe em branco para gerar um código interno.', max_length=13, null=True, unique=True, verbose_name='Código de Barras')),
            ],
        ),
    ]
