# Generated by Django 5.2.1 on 2025-07-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Folheado',
        ),
    ]
