# Generated by Django 5.2.1 on 2025-07-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_produto_folheado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome principal do produto, como aparecerá na nota e nas etiquetas.', max_length=200, unique=True, verbose_name='Nome do Produto')),
                ('tipo', models.CharField(choices=[('FO', 'Folheado'), ('OU', 'Ouro'), ('PR', 'Prata')], default='FO', help_text='Selecione o tipo do material do produto.', max_length=2, verbose_name='Tipo do Produto')),
                ('estoque', models.PositiveIntegerField(default=0, help_text='A quantidade atual de unidades deste produto disponíveis para venda.', verbose_name='Quantidade em Estoque')),
                ('gramas', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Informe o peso do produto em gramas (se for ouro).', max_digits=10, null=True, verbose_name='Peso (gramas)')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, help_text='O valor que você pagou pelo produto.', max_digits=10, null=True, verbose_name='Preço de Custo (R$)')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Margem de Lucro (%)')),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, verbose_name='Preço Final de Venda (R$)')),
                ('codigo_barras', models.CharField(blank=True, help_text='Digite um código de até 13 números ou deixe em branco para gerar um código interno.', max_length=13, null=True, unique=True, verbose_name='Código de Barras')),
            ],
        ),
        migrations.DeleteModel(
            name='Folheado',
        ),
    ]
