# Generated by Django 5.2.1 on 2025-07-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_delete_folheado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Preço Final de Venda (R$)'),
        ),
    ]
