# Generated by Django 5.2.1 on 2025-07-22 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_preco_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome do tipo de peça, como 'Anel', 'Brinco', etc.", max_length=100, unique=True, verbose_name='Tipo de Peça')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_peca',
            field=models.ForeignKey(blank=True, help_text="Selecione o tipo de peça, como 'Anel', 'Brinco', etc.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.tipopeca', verbose_name='Tipo de Peça'),
        ),
    ]
