# Generated by Django 5.2.1 on 2025-08-01 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_remessa_status'),
        ('produtos', '0005_tipopeca_produto_tipo_peca'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Selecione o fornecedor deste produto, se aplicável.', limit_choices_to=models.Q(('fornecedor', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente', verbose_name='Fornecedor'),
        ),
    ]
