# Generated by Django 5.2.1 on 2025-08-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('DEB', 'Cartão de Débito'), ('CRE', 'Cartão de Crédito'), ('DIN', 'Dinheiro'), ('OUT', 'Outro')], default='PIX', max_length=3, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.DeleteModel(
            name='MovimentacaoEstoque',
        ),
    ]
