# Generated by Django 5.2.1 on 2025-08-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_alter_venda_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='valor_total',
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix'), ('DEB', 'Cartão de Débito'), ('CRE', 'Cartão de Crédito'), ('DIN', 'Dinheiro'), ('OUT', 'Outro')], default='PIX', max_length=3, verbose_name='Forma de Pagamento'),
        ),
    ]
