# Generated by Django 5.2.1 on 2025-07-30 19:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0005_tipopeca_produto_tipo_peca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.BooleanField(default=False, help_text='Marque esta opção se o cadastro for de um fornecedor de produtos.', verbose_name='É Fornecedor?')),
                ('nome_completo', models.CharField(help_text='Nome do cliente ou razão social do fornecedor.', max_length=200, verbose_name='Nome Completo')),
                ('cpf_cnpj', models.CharField(blank=True, help_text='Documento para identificação fiscal.', max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('telefone_whatsapp', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone / WhatsApp')),
                ('endereco', models.TextField(blank=True, help_text='Informe o endereço completo (Rua, Número, Bairro, Cidade, Estado, CEP).', null=True, verbose_name='Endereço')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Cliente ou Fornecedor',
                'verbose_name_plural': 'Clientes e Fornecedores',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Remessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Saída')),
                ('data_prevista_acerto', models.DateField(blank=True, null=True, verbose_name='Data Prevista para Acerto')),
                ('data_acerto_final', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data do Acerto Final')),
                ('status', models.CharField(choices=[('ABERTO', 'Em Aberto'), ('FINALIZADO', 'Finalizado')], default='ABERTO', max_length=10, verbose_name='Status da Remessa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remessas', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Remessa de Consignado',
                'verbose_name_plural': 'Remessas de Consignado',
                'ordering': ['-data_saida'],
            },
        ),
        migrations.CreateModel(
            name='ItemRemessa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('preco_venda_unitario_na_saida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário na Saída')),
                ('status_item', models.CharField(choices=[('CONSIGNADO', 'Consignado'), ('VENDIDO', 'Vendido'), ('DEVOLVIDO', 'Devolvido')], default='CONSIGNADO', max_length=12, verbose_name='Status do Item')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto')),
                ('remessa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='clientes.remessa', verbose_name='Remessa')),
            ],
            options={
                'verbose_name': 'Item da Remessa',
                'verbose_name_plural': 'Itens da Remessa',
                'unique_together': {('remessa', 'produto')},
            },
        ),
    ]
