# Generated by Django 5.2.1 on 2025-07-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipoFornecedor',
            field=models.CharField(blank=True, choices=[('FO', 'Folheado'), ('OU', 'Ouro'), ('PR', 'Prata')], default='FO', help_text='Selecione o tipo do material que o fornecedor fornece.', max_length=2, null=True, verbose_name='Produto Fornecido'),
        ),
    ]
