# Generated by Django 5.2.1 on 2025-07-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_tipofornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipoFornecedor',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_fornecedor',
            field=models.CharField(blank=True, choices=[('FO', 'Folheado'), ('OU', 'Ouro'), ('PR', 'Prata'), ('OT', 'Outros')], default='FO', help_text='Selecione o tipo do material que o fornecedor fornece.', max_length=2, null=True, verbose_name='Produto Fornecido'),
        ),
    ]
