# Generated by Django 5.2.1 on 2025-07-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_tipofornecedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, help_text='Informe o bairro do cliente ou fornecedor.', max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, help_text='Informe o CEP.', max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, help_text='Informe a cidade do cliente ou fornecedor.', max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, help_text='Informe o complemento do endereço (se houver).', max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, help_text='Informe o estado (UF) do cliente ou fornecedor.', max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, help_text='Informe o número do endereço (casa, apartamento, etc.).', max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(blank=True, help_text='Informe a rua do cliente ou fornecedor.', max_length=200, null=True, verbose_name='Rua'),
        ),
    ]
