# Generated by Django 5.2.1 on 2025-07-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_endereco_cliente_bairro_cliente_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='', help_text='Informe o bairro do cliente ou fornecedor.', max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='', help_text='Informe o CEP.', max_length=10, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='', help_text='Informe a cidade do cliente ou fornecedor.', max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(default='', help_text='Documento para identificação fiscal.', max_length=18, unique=True, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='', help_text='Informe o estado (UF) do cliente ou fornecedor.', max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default='', help_text='Informe o número do endereço (casa, apartamento, etc.).', max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rua',
            field=models.CharField(default='', help_text='Informe a rua do cliente ou fornecedor.', max_length=200, verbose_name='Rua'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_whatsapp',
            field=models.CharField(default='', max_length=15, verbose_name='Telefone / WhatsApp'),
            preserve_default=False,
        ),
    ]
