# Generated by Django 5.2.1 on 2025-07-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_bairro_alter_cliente_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remessa',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Em Aberto'), ('FINALIZADO', 'Finalizado')], default='FINALIZADO', max_length=10, verbose_name='Status da Remessa'),
        ),
    ]
